"""R-parity tests for StackedDiD's vcov_type threading (Phase 1b 2/8).

Pins Python StackedDiD output against R `clubSandwich::vcovCR(lm(weights=Q,...),
type="CR1S"|"CR2") + coef_test()$df_Satt` and `Wald_test(test="HTZ")$df_denom`
at atol=1e-10. The clubSandwich port in `diff_diff/linalg.py` (PR #475)
supplies the underlying WLS-CR2 algebra; this file verifies that StackedDiD's
call into `solve_ols(weights=composed_weights, vcov_type=...)` produces output
consistent with the R reference, including the Bell-McCaffrey Satterthwaite
DOF threading at both the per-event-time level and the post-period-average
contrast level.

Goldens are generated by `benchmarks/R/generate_stacked_did_golden.R` (loads
the pre-stacked panel CSV at `benchmarks/data/stacked_did_test_panel.csv`,
fits `lm(weights=Q,...)`, dumps CR1S + CR2-BM + Satterthwaite DOF for the
event-study coefficients AND the post-period-average ATT contrast at both
`cluster=unit` and `cluster=unit_subexp`).

Note on `CR1` vs `CR1S`: diff-diff's HC1 + cluster uses Stata-style
`G/(G-1) * (n-1)/(n-p)` finite-sample correction, which matches
`clubSandwich::vcovCR(type="CR1S")`. The plain `clubSandwich::vcovCR(type="CR1")`
omits the `(n-1)/(n-p)` term and diverges by ~1.4% on this fixture.
"""

from __future__ import annotations

import json
import os

import numpy as np
import pytest
from scipy.optimize import brentq
from scipy.stats import t as t_dist

from diff_diff import StackedDiD
from diff_diff.prep_dgp import generate_staggered_data

_GOLDEN_PATH = os.path.join(
    os.path.dirname(__file__),
    "..",
    "benchmarks",
    "data",
    "stacked_did_golden.json",
)
_R_FIXTURE_AVAILABLE = os.path.exists(_GOLDEN_PATH)


@pytest.fixture(scope="module")
def goldens():
    if not _R_FIXTURE_AVAILABLE:
        pytest.skip(
            "stacked_did_golden.json not generated; run "
            "Rscript benchmarks/R/generate_stacked_did_golden.R"
        )
    with open(_GOLDEN_PATH) as f:
        return json.load(f)


@pytest.fixture(scope="module")
def panel():
    """Same panel descriptor as the R fixture; must match exactly."""
    return generate_staggered_data(
        n_units=50,
        n_periods=8,
        cohort_periods=[3, 5, 7],
        never_treated_frac=0.3,
        treatment_effect=2.0,
        dynamic_effects=False,
        seed=20260521,
    )


def _fit(panel, vcov_type, cluster):
    est = StackedDiD(kappa_pre=2, kappa_post=2, vcov_type=vcov_type, cluster=cluster)
    return est.fit(
        panel,
        outcome="outcome",
        unit="unit",
        time="period",
        first_treat="first_treat",
        aggregate="event_study",
    )


def _es_se_vector(res, event_times_non_ref):
    """Extract event-study SE vector in the order given by event_times_non_ref."""
    return np.array([res.event_study_effects[h]["se"] for h in event_times_non_ref])


def _recover_dof_from_ci(att, se, ci_hi, alpha):
    """Recover DOF used by safe_inference from the CI half-width.

    Inverse of `ci_hi = att + se * t.ppf(1 - alpha/2, df)`. Used to assert
    the BM Satterthwaite DOF threaded correctly into the result-class
    inference fields without relying on internal estimator state.

    Raises ValueError if the inversion fails (e.g., when safe_inference
    used the normal distribution instead of t — meaning the BM DOF did
    NOT propagate and the test should FAIL, not silently skip).
    """
    half_width = ci_hi - att
    t_crit = half_width / se
    target_alpha = alpha / 2  # 0.025 for alpha=0.05

    def f(df):
        return t_dist.sf(t_crit, df) - target_alpha

    # Use a wide bracket; brentq raises ValueError if no root.
    return brentq(f, 1.0, 1e9, xtol=1e-9)


class TestStackedDiDParityR:
    """Pin StackedDiD output against clubSandwich at atol=1e-10.

    Coverage:
      - hc1 + cluster=unit SE matches CR1S (Stata-style correction)
      - hc2_bm + cluster=unit SE matches CR2 Bell-McCaffrey
      - hc2_bm + cluster=unit per-event-time DOF matches coef_test()$df_Satt
      - hc2_bm + cluster=unit overall ATT DOF matches Wald_test(HTZ)$df_denom
      - hc2_bm + cluster=unit_subexp SE matches CR2 (symmetric)

    The DOF parity tests use CI-width inversion to recover the DOF that
    `safe_inference` actually used. If the BM DOF doesn't propagate (the
    R1 P0 bug), `safe_inference` uses the normal distribution and the
    half-width is `se * 1.96`, which inverts to `df → infinity` — that
    inversion FAILS within the bracket [1, 1e9] and raises ValueError,
    which surfaces as a test failure (not a silent skip).
    """

    def test_hc1_se_matches_clubsandwich_cr1s_unit_cluster(self, goldens, panel):
        """Default cluster=unit, vcov_type=hc1 matches R `vcovCR(type='CR1S')`.

        See module docstring: 'CR1S' (Stata-style) is the correct comparison
        target; plain 'CR1' (clubSandwich's no-(n-1)/(n-p) form) would diverge
        by ~1.4% on this fixture.
        """
        event_times = goldens["meta"]["event_times_non_ref"]
        r_se = np.array(goldens["unit"]["se_cr1_es"])
        res = _fit(panel, vcov_type="hc1", cluster="unit")
        py_se = _es_se_vector(res, event_times)
        np.testing.assert_allclose(
            py_se,
            r_se,
            atol=1e-10,
            rtol=1e-10,
            err_msg=(
                "StackedDiD hc1 event-study SE must match clubSandwich CR1S at atol=1e-10. "
                "Note: target is CR1S (Stata-style), not plain CR1."
            ),
        )

    def test_hc2_bm_se_matches_clubsandwich_cr2_unit_cluster(self, goldens, panel):
        """cluster=unit, vcov_type=hc2_bm matches R `vcovCR(type='CR2')`."""
        event_times = goldens["meta"]["event_times_non_ref"]
        r_se = np.array(goldens["unit"]["se_cr2_es"])
        res = _fit(panel, vcov_type="hc2_bm", cluster="unit")
        py_se = _es_se_vector(res, event_times)
        np.testing.assert_allclose(
            py_se,
            r_se,
            atol=1e-10,
            rtol=1e-10,
            err_msg="StackedDiD hc2_bm event-study SE must match clubSandwich CR2 at atol=1e-10",
        )

    def test_hc2_bm_per_event_dof_matches_coef_test_df_satt_unit_cluster(self, goldens, panel):
        """Per-event-time BM DOF propagated via safe_inference matches
        `coef_test(..., vcov=CR2)$df_Satt`.

        Recovers the DOF from CI half-width inversion. If BM DOF didn't
        propagate, `safe_inference` would use the normal distribution
        (df=None) and the recovery would fail with ValueError — which
        surfaces as a test failure, NOT a silent skip. This was the R1 P0
        failure mode caught by CI codex.
        """
        event_times = goldens["meta"]["event_times_non_ref"]
        r_dof = np.array(goldens["unit"]["dof_bm_es"])
        res = _fit(panel, vcov_type="hc2_bm", cluster="unit")
        validated_count = 0
        for h, r_dof_h in zip(event_times, r_dof):
            es = res.event_study_effects[h]
            att, se, ci_hi = es["effect"], es["se"], es["conf_int"][1]
            # If propagation failed, this raises ValueError → test fails.
            df_python = _recover_dof_from_ci(att, se, ci_hi, res.alpha)
            np.testing.assert_allclose(
                df_python,
                r_dof_h,
                atol=1e-6,
                rtol=1e-6,
                err_msg=(
                    f"BM DOF for event_time={h} must match clubSandwich coef_test "
                    f"df_Satt; recovered df_python={df_python}, R df_Satt={r_dof_h}"
                ),
            )
            validated_count += 1
        # Hard guard: ensure we actually validated every coefficient.
        assert validated_count == len(event_times), (
            f"Expected to validate DOF for all {len(event_times)} event-time "
            f"coefficients, only validated {validated_count}"
        )

    def test_hc2_bm_overall_att_dof_matches_wald_test_htz_unit_cluster(self, goldens, panel):
        """Overall ATT BM DOF matches `Wald_test(HTZ)$df_denom` (per review P2:
        the post-period-average contrast was missing from the prior fixture)."""
        r_dof_overall = float(goldens["unit"]["dof_bm_overall"])
        res = _fit(panel, vcov_type="hc2_bm", cluster="unit")
        att, se, ci_hi = res.overall_att, res.overall_se, res.overall_conf_int[1]
        df_python = _recover_dof_from_ci(att, se, ci_hi, res.alpha)
        np.testing.assert_allclose(
            df_python,
            r_dof_overall,
            atol=1e-6,
            rtol=1e-6,
            err_msg=(
                f"Overall ATT BM DOF must match clubSandwich Wald_test(HTZ) "
                f"df_denom; recovered df_python={df_python}, R df={r_dof_overall}"
            ),
        )

    def test_hc2_bm_se_matches_clubsandwich_cr2_unit_subexp_cluster(self, goldens, panel):
        """Same parity for the alternate cluster level."""
        event_times = goldens["meta"]["event_times_non_ref"]
        r_se = np.array(goldens["unit_subexp"]["se_cr2_es"])
        res = _fit(panel, vcov_type="hc2_bm", cluster="unit_subexp")
        py_se = _es_se_vector(res, event_times)
        np.testing.assert_allclose(
            py_se,
            r_se,
            atol=1e-10,
            rtol=1e-10,
            err_msg=(
                "StackedDiD hc2_bm + cluster=unit_subexp must match "
                "clubSandwich CR2 at atol=1e-10"
            ),
        )

    def test_hc2_bm_overall_att_dof_matches_wald_test_htz_unit_subexp_cluster(self, goldens, panel):
        """Symmetric overall ATT DOF parity at the alternate cluster level."""
        r_dof_overall = float(goldens["unit_subexp"]["dof_bm_overall"])
        res = _fit(panel, vcov_type="hc2_bm", cluster="unit_subexp")
        att, se, ci_hi = res.overall_att, res.overall_se, res.overall_conf_int[1]
        df_python = _recover_dof_from_ci(att, se, ci_hi, res.alpha)
        np.testing.assert_allclose(
            df_python,
            r_dof_overall,
            atol=1e-6,
            rtol=1e-6,
            err_msg=(
                f"Overall ATT BM DOF (unit_subexp) must match clubSandwich; "
                f"recovered df_python={df_python}, R df={r_dof_overall}"
            ),
        )
