"""R-parity tests for WooldridgeDiD OLS path vcov_type variants.

Pins ``WooldridgeDiD(method='ols', vcov_type=...)`` against R's
``clubSandwich`` (CR2 + Bell-McCaffrey Satterthwaite DOF) and ``sandwich``
(HC2) on the fixed-seed panel at ``benchmarks/data/wooldridge_test_panel.csv``.
Goldens are generated by ``benchmarks/R/generate_wooldridge_golden.R``
(requires ``clubSandwich >= 0.7.0`` and ``sandwich >= 3.0.0``).

The ``hc1`` variant is NOT pinned against R here because the diff-diff
within-transform finite-sample correction ``(n-1)/(n-k_dm)`` differs from
``lm + clubSandwich::vcovCR(type="CR1S")``'s ``(n-1)/(n-k_total)`` correction;
see ``docs/methodology/REGISTRY.md`` "Variance families" → "Deviation from R"
for the algebra. The hc1 path is locked instead by
``tests/test_wooldridge.py::TestWooldridgeVcovType::test_hc1_se_bit_equal_to_pre_pr_baseline``
at ``atol=1e-14``.
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import pytest
from scipy import stats
from scipy.optimize import brentq

from diff_diff.wooldridge import WooldridgeDiD

GOLDEN_PATH = Path(__file__).parent.parent / "benchmarks" / "data" / "wooldridge_golden.json"
PANEL_PATH = Path(__file__).parent.parent / "benchmarks" / "data" / "wooldridge_test_panel.csv"

_R_FIXTURE_AVAILABLE = GOLDEN_PATH.is_file() and PANEL_PATH.is_file()


def _recover_dof_from_ci(att: float, se: float, ci_hi: float, alpha: float) -> float:
    """Recover the t-distribution DOF used to build a CI from its half-width.

    Inverts ``ci_hi = att + t.ppf(1 - alpha/2, df) * se`` for ``df``. Used to
    cross-check the BM contrast DOF threaded into Python's aggregated
    inference without requiring the dataclass to expose the DOF as a direct
    field (mirrors the SunAbraham / StackedDiD R-parity pattern).
    """
    t_crit_implied = (ci_hi - att) / se
    return brentq(
        lambda df: stats.t.ppf(1 - alpha / 2, df) - t_crit_implied,
        1.5,
        10000.0,
    )


@pytest.fixture(scope="module")
def golden() -> dict:
    if not _R_FIXTURE_AVAILABLE:
        pytest.skip(
            "R-parity fixture not present. Run "
            "`Rscript benchmarks/R/generate_wooldridge_golden.R` "
            "to regenerate `benchmarks/data/wooldridge_golden.json`."
        )
    with GOLDEN_PATH.open("r") as f:
        return json.loads(f.read())


@pytest.fixture(scope="module")
def panel() -> pd.DataFrame:
    if not _R_FIXTURE_AVAILABLE:
        pytest.skip("R-parity fixture not present.")
    return pd.read_csv(PANEL_PATH)


@pytest.mark.skipif(not _R_FIXTURE_AVAILABLE, reason="R-parity fixture not present.")
class TestWooldridgeParityR:
    """Pin Python WooldridgeDiD OLS vcov_type output against R `lm` + clubSandwich / sandwich."""

    def test_interaction_coefs_match_lm(self, golden: dict, panel: pd.DataFrame) -> None:
        """Point estimates (treatment-cell coefficients) match R `lm()` at atol=1e-10.

        Identical across all 4 vcov_type variants (only SE differs); pin via
        `vcov_type='hc2_bm'` (full-dummy branch).
        """
        res = WooldridgeDiD(method="ols", vcov_type="hc2_bm").fit(
            panel, outcome="y", unit="unit", time="time", cohort="cohort"
        )
        r_keys = [(d["g"], d["t"]) for d in golden["point_estimates"]["gt_keys"]]
        r_coefs = golden["point_estimates"]["interaction_coefs"]
        for i, (g, t) in enumerate(r_keys):
            py_att = res.group_time_effects[(g, t)]["att"]
            assert py_att == pytest.approx(
                r_coefs[i], abs=1e-10
            ), f"(g={g}, t={t}): Py={py_att:.10f} R={r_coefs[i]:.10f}"

    def test_hc2_bm_per_coef_se_matches_clubsandwich_cr2(
        self, golden: dict, panel: pd.DataFrame
    ) -> None:
        """Per-treatment-cell CR2-BM SE matches `clubSandwich::vcovCR(..., type="CR2")` at atol=1e-10."""
        res = WooldridgeDiD(method="ols", vcov_type="hc2_bm").fit(
            panel, outcome="y", unit="unit", time="time", cohort="cohort"
        )
        r_keys = [(d["g"], d["t"]) for d in golden["point_estimates"]["gt_keys"]]
        r_ses = golden["hc2_bm"]["per_coef_se"]
        for i, (g, t) in enumerate(r_keys):
            py_se = res.group_time_effects[(g, t)]["se"]
            assert py_se == pytest.approx(
                r_ses[i], abs=1e-10
            ), f"(g={g}, t={t}): Py SE={py_se:.10f} R SE={r_ses[i]:.10f}"

    def test_hc2_bm_overall_att_se_matches_clubsandwich_cr2(
        self, golden: dict, panel: pd.DataFrame
    ) -> None:
        """Overall ATT SE matches the linear-combination SE from `clubSandwich::vcovCR(..., type="CR2")`."""
        res = WooldridgeDiD(method="ols", vcov_type="hc2_bm").fit(
            panel, outcome="y", unit="unit", time="time", cohort="cohort"
        )
        r_se = golden["hc2_bm"]["overall_att_se"]
        assert res.overall_se == pytest.approx(r_se, abs=1e-10)

    def test_hc2_bm_overall_att_contrast_dof_matches_wald_test_htz(
        self, golden: dict, panel: pd.DataFrame
    ) -> None:
        """Overall ATT BM contrast DOF matches `Wald_test(test="HTZ")$df_denom` at atol=1e-10.

        Inverts the Python CI half-width to recover the t-distribution DOF
        (the WooldridgeDiDResults dataclass does not expose the BM contrast
        DOF as a direct field; same approach as SunAbraham PR #472 /
        StackedDiD PR #479).
        """
        res = WooldridgeDiD(method="ols", vcov_type="hc2_bm").fit(
            panel, outcome="y", unit="unit", time="time", cohort="cohort"
        )
        py_dof = _recover_dof_from_ci(
            res.overall_att, res.overall_se, res.overall_conf_int[1], res.alpha
        )
        r_dof = golden["hc2_bm"]["overall_att_contrast_dof"]
        # brentq inversion tolerance + scipy stats roundtrip: 1e-6 is comfortable
        # for a DOF in the 1.5..1000 range. The underlying clubSandwich CR2
        # vcov matches at machine precision (~6e-16 on per-coef SE).
        assert py_dof == pytest.approx(r_dof, abs=1e-6)

    def test_classical_se_matches_lm_summary(self, golden: dict, panel: pd.DataFrame) -> None:
        """`vcov_type='classical'` (drops auto-cluster) matches `summary(lm(...))$coefficients` SE."""
        res = WooldridgeDiD(method="ols", vcov_type="classical").fit(
            panel, outcome="y", unit="unit", time="time", cohort="cohort"
        )
        r_keys = [(d["g"], d["t"]) for d in golden["point_estimates"]["gt_keys"]]
        r_ses = golden["classical"]["per_coef_se"]
        for i, (g, t) in enumerate(r_keys):
            py_se = res.group_time_effects[(g, t)]["se"]
            assert py_se == pytest.approx(r_ses[i], abs=1e-10)
        assert res.overall_se == pytest.approx(golden["classical"]["overall_att_se"], abs=1e-10)

    def test_hc2_se_matches_sandwich_vcovhc(self, golden: dict, panel: pd.DataFrame) -> None:
        """`vcov_type='hc2'` (drops auto-cluster) matches `sandwich::vcovHC(type="HC2")` SE."""
        res = WooldridgeDiD(method="ols", vcov_type="hc2").fit(
            panel, outcome="y", unit="unit", time="time", cohort="cohort"
        )
        r_keys = [(d["g"], d["t"]) for d in golden["point_estimates"]["gt_keys"]]
        r_ses = golden["hc2"]["per_coef_se"]
        for i, (g, t) in enumerate(r_keys):
            py_se = res.group_time_effects[(g, t)]["se"]
            assert py_se == pytest.approx(r_ses[i], abs=1e-10)
        assert res.overall_se == pytest.approx(golden["hc2"]["overall_att_se"], abs=1e-10)
